# Book settings
title: Econ/Poli 5 
author: David Arnold
logo: images/icon.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  baseurl : "https://darnold199.github.io/econpoli5/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  #comments:
    #hypothesis: false
    #utterances: 
      #repo: "darnold199/econ5"
  
launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/darnold199/econpoli5
  path_to_book : ""
  branch       : master

sphinx:
  config:
    html_show_copyright: false
